name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Check code formatting and linting
        run: bunx --bun @biomejs/biome check .

      - name: Run unit tests
        run: bun test tests/unit

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps

      - name: Run integration tests
        run: bunx playwright test tests/integration
