name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Check code formatting and linting
        run: npx @biomejs/biome check .

      - name: Run tests
        run: npx jest --testMatch="**/tests/**/*.spec.js"
